import React, { Fragment } from 'react'

const DummyText = () => (
  <Fragment>
    <p>Pommy ipsum bog roll chav anorak bogroll Doctor Who down the local lass, by 'eck love nicked what a mug treacle doing my head in bog off by 'eck love, down the village green proper Geordie it's me peepers Sherlock done up like a kipper proper. Lass chav terribly spam fritters tallywhacker for sooth, slappers wellies muck about off t'pub, challenge you to a duel pulled a right corker crumpets have a kip. Amelia Pond leisurely splendid jolly lost her marbles yorkshire mixture, copper bog roll and thus completely starkers black pudding, warts and all rambunctious come hither cotton on. </p>

    <p>Terribly copper god save the queen pulled out the eating irons Dr. Watson devonshire cream tea whizz the chippy well chuffed, manky collywobbles a total jessie round our gaff River Song pants. Bad Wolf jolly hockey sticks red telephone box eton mess Doctor Who Sonic Screwdriver, god save the queen ear hole smeg head 10 pence mix collywobbles fried toast, flog a dead horse golly bargain Betty two weeks on't trot. Flip flops bloke devonshire cream tea upper class indeed big light, working class corgi spam fritters horses for courses. Come hither posh nosh have a bash horses for courses what a load of cobblers terribly the lakes the chippy, rambunctious fish and chips a cuppa bread and butter pudding a week on Sunday. </p>

    <p>'tis manky I bid you good day warts and all bovver boots pork dripping challenge you to a duel, don't get your knickers in a twist spam fritters golly spam fritters off the hook, brilliant oopsy-daisies good old fashioned knees up daft cow stew and dumps. Blimey sod's law don't get your knickers in a twist know your onions Essex girls, cotton on slappers Union Jack golly gosh, ended up brown bread a bit miffed who brought loaf. Yorkshire pudding whizz naff cotton on laughing gear I'm off to Bedfordshire sorted it, make a brew Sonic Screwdriver pompous bog roll gutted, her Majesty's pleasure jolly good trouble and strife codswallop goggledegook. </p>

    <p>Baffled on his tod any road, best be off put me soaps back on man and his whippet old chap well fit, you 'avin a laugh gobsmacked Big Ben because there was nothing on the gogglebox gosh. Pikey beefeater I'd reet fancy a bottled it nutter doofer, golly River Song what a load of guff could be a bit of a git. 'ar kid a right royal knees up warts and all Victoria sponge cake working class unhand me sir could murder a pint, slap-head punter eton mess wibbly-wobbly timey-wimey stuff owt, 'ar kid down the village green every fortnight yorkshire mixture Geordie. Cotton on bugger Time Lord wind up football skive, anorak supper off with her head challenge you to a duel, marvelous old chap pork dripping bent as a nine bob note. </p>

    <p>Ear hole scally on't goggle box see a man about a dog stupendous houlligan ey up duck I'm off to Bedfordshire whizz chinwag have a butcher's at this spend a penny Prince Charles, doofer roast beef driving a mini nose rag numpty cheerio ended up brown bread sod's law fancied a flutter gravy cheese and chips loo. Bow ties are cool bits 'n bobs a right toff bogroll bloody shambles get away with ya old chap cottage pie, bow ties are cool willy every fortnight codswallop argy-bargy horses for courses, and thus blimey chips wedding tackle balderdash pants ey up duck. Marvelous on his bill numbskull muck about sausage roll, ear hole toad in the whole scrubber knee high to a grasshopper i'll be a monkey's uncle spiffing, knee high to a grasshopper i'll be a monkey's uncle a bit wonky willy. </p>

    <p>Pennyboy marmite rubbish bangers and mash 'tis alright duck it's the bees knees, knee high to a grasshopper i'll be a monkey's uncle loo cheerio teacakes cheerio, Big Ben we'll be 'avin less of that scones up the duff flog. Jellied eels clock round the earhole scrubber loo on his tod upper class apple and pears one would be honoured to pompous, jolly good wellies accordingly scouser a bit wonky toad in the whole supper. I could reet fancy a Geordie marmite bovver boots fish and chips it's me peepers Union Jack up North daft cow bow ties are cool doofer completely starkers, warts and all rather get away with ya wind up doolally chav a tenner completely starkers muck about. </p>

    <p>Driving a mini in a pickle a total jessie got his end away rambunctious a cuppa, Southeners clock round the earhole in the goolies. Bloody shambles shortbread how's your father conked him one on the nose the old bill, absobloodylootely Northeners. The dog's dinner a cuppa have a gander wibbly-wobbly timey-wimey stuff snotty nosed brat bog roll, pot noodle codswallop ey up treacle horses for courses, Moriarty earwig and we all like figgy pudding a cuppa. A diamond geezer fork out rubbish a total jessie hadn't done it in donkey's years hard cheese old boy, naff one off rambunctious. Brown sauce trouble and strife what a mug have a butcher's at this 10 pence mix, got his end away porky-pies. </p>

    <p>Bread and butter pudding it's the bees knees horses for courses gosh, Moriarty slappers. Bloody shambles make a brew on his tod scrumpy bit of a Jack the lad alright duck, alright geezer ask your mother if air one's dirty linen Elementary my dear Watson. At the boozer crumpets throw a paddy yorkshire pudding scones doing my nut in brilliant, it's me peepers warts and all Bob's your uncle fish fingers and custard spam fritters. I'm off to Bedfordshire the fuzz black cab brainbox complete mare snotty nosed brat, spam fritters off the hook naff. </p>

    <p>Pommy ipsum bog roll chav anorak bogroll Doctor Who down the local lass, by 'eck love nicked what a mug treacle doing my head in bog off by 'eck love, down the village green proper Geordie it's me peepers Sherlock done up like a kipper proper. Lass chav terribly spam fritters tallywhacker for sooth, slappers wellies muck about off t'pub, challenge you to a duel pulled a right corker crumpets have a kip. Amelia Pond leisurely splendid jolly lost her marbles yorkshire mixture, copper bog roll and thus completely starkers black pudding, warts and all rambunctious come hither cotton on. </p>

    <p>Terribly copper god save the queen pulled out the eating irons Dr. Watson devonshire cream tea whizz the chippy well chuffed, manky collywobbles a total jessie round our gaff River Song pants. Bad Wolf jolly hockey sticks red telephone box eton mess Doctor Who Sonic Screwdriver, god save the queen ear hole smeg head 10 pence mix collywobbles fried toast, flog a dead horse golly bargain Betty two weeks on't trot. Flip flops bloke devonshire cream tea upper class indeed big light, working class corgi spam fritters horses for courses. Come hither posh nosh have a bash horses for courses what a load of cobblers terribly the lakes the chippy, rambunctious fish and chips a cuppa bread and butter pudding a week on Sunday. </p>

    <p>'tis manky I bid you good day warts and all bovver boots pork dripping challenge you to a duel, don't get your knickers in a twist spam fritters golly spam fritters off the hook, brilliant oopsy-daisies good old fashioned knees up daft cow stew and dumps. Blimey sod's law don't get your knickers in a twist know your onions Essex girls, cotton on slappers Union Jack golly gosh, ended up brown bread a bit miffed who brought loaf. Yorkshire pudding whizz naff cotton on laughing gear I'm off to Bedfordshire sorted it, make a brew Sonic Screwdriver pompous bog roll gutted, her Majesty's pleasure jolly good trouble and strife codswallop goggledegook. </p>

    <p>Baffled on his tod any road, best be off put me soaps back on man and his whippet old chap well fit, you 'avin a laugh gobsmacked Big Ben because there was nothing on the gogglebox gosh. Pikey beefeater I'd reet fancy a bottled it nutter doofer, golly River Song what a load of guff could be a bit of a git. 'ar kid a right royal knees up warts and all Victoria sponge cake working class unhand me sir could murder a pint, slap-head punter eton mess wibbly-wobbly timey-wimey stuff owt, 'ar kid down the village green every fortnight yorkshire mixture Geordie. Cotton on bugger Time Lord wind up football skive, anorak supper off with her head challenge you to a duel, marvelous old chap pork dripping bent as a nine bob note. </p>

    <p>Ear hole scally on't goggle box see a man about a dog stupendous houlligan ey up duck I'm off to Bedfordshire whizz chinwag have a butcher's at this spend a penny Prince Charles, doofer roast beef driving a mini nose rag numpty cheerio ended up brown bread sod's law fancied a flutter gravy cheese and chips loo. Bow ties are cool bits 'n bobs a right toff bogroll bloody shambles get away with ya old chap cottage pie, bow ties are cool willy every fortnight codswallop argy-bargy horses for courses, and thus blimey chips wedding tackle balderdash pants ey up duck. Marvelous on his bill numbskull muck about sausage roll, ear hole toad in the whole scrubber knee high to a grasshopper i'll be a monkey's uncle spiffing, knee high to a grasshopper i'll be a monkey's uncle a bit wonky willy. </p>

    <p>Pennyboy marmite rubbish bangers and mash 'tis alright duck it's the bees knees, knee high to a grasshopper i'll be a monkey's uncle loo cheerio teacakes cheerio, Big Ben we'll be 'avin less of that scones up the duff flog. Jellied eels clock round the earhole scrubber loo on his tod upper class apple and pears one would be honoured to pompous, jolly good wellies accordingly scouser a bit wonky toad in the whole supper. I could reet fancy a Geordie marmite bovver boots fish and chips it's me peepers Union Jack up North daft cow bow ties are cool doofer completely starkers, warts and all rather get away with ya wind up doolally chav a tenner completely starkers muck about. </p>

    <p>Driving a mini in a pickle a total jessie got his end away rambunctious a cuppa, Southeners clock round the earhole in the goolies. Bloody shambles shortbread how's your father conked him one on the nose the old bill, absobloodylootely Northeners. The dog's dinner a cuppa have a gander wibbly-wobbly timey-wimey stuff snotty nosed brat bog roll, pot noodle codswallop ey up treacle horses for courses, Moriarty earwig and we all like figgy pudding a cuppa. A diamond geezer fork out rubbish a total jessie hadn't done it in donkey's years hard cheese old boy, naff one off rambunctious. Brown sauce trouble and strife what a mug have a butcher's at this 10 pence mix, got his end away porky-pies. </p>

    <p>Bread and butter pudding it's the bees knees horses for courses gosh, Moriarty slappers. Bloody shambles make a brew on his tod scrumpy bit of a Jack the lad alright duck, alright geezer ask your mother if air one's dirty linen Elementary my dear Watson. At the boozer crumpets throw a paddy yorkshire pudding scones doing my nut in brilliant, it's me peepers warts and all Bob's your uncle fish fingers and custard spam fritters. I'm off to Bedfordshire the fuzz black cab brainbox complete mare snotty nosed brat, spam fritters off the hook naff. </p>
  </Fragment>
)

export default DummyText
